<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE sv:node [
        <!ELEMENT sv:node (sv:property|sv:node)*>
        <!ATTLIST sv:node
                sv:name CDATA #REQUIRED
                xmlns:sv CDATA #IMPLIED>
        <!ELEMENT sv:property (sv:value)*>
        <!ATTLIST sv:property
                sv:multiple CDATA #IMPLIED
                sv:name CDATA #REQUIRED
                sv:type CDATA #REQUIRED>
        <!ELEMENT sv:value (#PCDATA)>
        ]>
<sv:node xmlns:sv="http://www.jcp.org/jcr/sv/1.0" sv:name="hst:configurations">
  <sv:property sv:name="jcr:primaryType" sv:type="Name">
    <sv:value>hst:configurations</sv:value>
  </sv:property>
  <sv:node sv:name="hst:default">
    <sv:property sv:name="jcr:primaryType" sv:type="Name">
      <sv:value>hst:configuration</sv:value>
    </sv:property>
    <sv:node sv:name="hst:sitemap">
      <sv:property sv:name="jcr:primaryType" sv:type="Name">
        <sv:value>hst:sitemap</sv:value>
      </sv:property>
    </sv:node>
    <sv:node sv:name="hst:pages">
      <sv:property sv:name="jcr:primaryType" sv:type="Name">
        <sv:value>hst:pages</sv:value>
      </sv:property>
    </sv:node>
    <sv:node sv:name="hst:components">
      <sv:property sv:name="jcr:primaryType" sv:type="Name">
        <sv:value>hst:components</sv:value>
      </sv:property>
    </sv:node>
    <sv:node sv:name="hst:sitemenus">
      <sv:property sv:name="jcr:primaryType" sv:type="Name">
        <sv:value>hst:sitemenus</sv:value>
      </sv:property>
    </sv:node>
    <sv:node sv:name="hst:sitemapitemhandlers">
      <sv:property sv:name="jcr:primaryType" sv:type="Name">
        <sv:value>hst:sitemapitemhandlers</sv:value>
      </sv:property>
    </sv:node>
  </sv:node>
  <sv:node sv:name="common">
    <sv:property sv:name="jcr:primaryType" sv:type="Name">
      <sv:value>hst:configuration</sv:value>
    </sv:property>
  </sv:node>
  <sv:node sv:name="wkmulti">
    <sv:property sv:name="jcr:primaryType" sv:type="Name">
      <sv:value>hst:configuration</sv:value>
    </sv:property>
    <sv:property sv:name="hst:inheritsfrom" sv:type="String" sv:multiple="true">
      <sv:value>../common</sv:value>
    </sv:property>
  </sv:node>
  <sv:node sv:name="wkmultidrie">
    <sv:property sv:name="jcr:primaryType" sv:type="Name">
      <sv:value>hst:configuration</sv:value>
    </sv:property>
    <sv:property sv:name="hst:inheritsfrom" sv:type="String" sv:multiple="true">
      <sv:value>../common</sv:value>
    </sv:property>
  </sv:node>
  <sv:node sv:name="corporate">
    <sv:property sv:name="jcr:primaryType" sv:type="Name">
      <sv:value>hst:configuration</sv:value>
    </sv:property>
    <sv:property sv:name="hst:inheritsfrom" sv:type="String" sv:multiple="true">
      <sv:value>../common</sv:value>
    </sv:property>
  </sv:node>
  <sv:node sv:name="wkmultitwee">
    <sv:property sv:name="jcr:primaryType" sv:type="Name">
      <sv:value>hst:configuration</sv:value>
    </sv:property>
    <sv:property sv:name="hst:inheritsfrom" sv:type="String" sv:multiple="true">
      <sv:value>../common</sv:value>
    </sv:property>
  </sv:node>
</sv:node>
